### ISSUE TITLE
No user feedback when interacting with buttons on article

### ISSUE THREAD

**Issue by lucas-dclrcq** [oknozor/manucure#4]
When I click on buttons on an article (Archive, Delete, Star), it works but no feedback is shown on success or error.

I propose that on clicking on Archive or Delete, the user should be redirected to the main page.

On clicking on the star button, the star button should become fully black to show that the operation succeeded.

We should also have a common way to show errors, one of the following would work
- redirecting to an error page
- showing a toaster with the error
- shutting down the computer of the user

**Comment by oknozor** [comment]
Addressed in b81a523259681e6fc3203d16cd61ac10e5354bf8 39f6c8ab6abd17f1f4e2b3f36b603255bf8ba697 a5ac9ba8d12e361d4300b58b1340aabc1d1c2918
